/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminConfig {
  'email' : string,
  'adminName' : string,
  'upiId' : string,
  'mobile' : MobileNumber,
  'qrCodeBlobId' : ExternalBlob,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Banner {
  'id' : bigint,
  'title' : string,
  'active' : boolean,
  'linkUrl' : string,
  'displayOrder' : bigint,
  'imageUrl' : string,
  'subtitle' : string,
}
export interface Category {
  'id' : bigint,
  'name' : string,
  'color' : string,
  'emoji' : string,
  'enabled' : boolean,
}
export interface CustomCode {
  'id' : bigint,
  'placement' : string,
  'code' : string,
  'icon' : string,
  'name' : string,
  'enabled' : boolean,
  'btnLabel' : string,
}
export type ExternalBlob = Uint8Array;
export interface JobItem {
  'id' : bigint,
  'title' : string,
  'applyLink' : string,
  'createdAt' : bigint,
  'enabled' : boolean,
  'category' : string,
  'department' : string,
  'lastDate' : string,
  'location' : string,
}
export type MobileNumber = string;
export interface NewsItem {
  'id' : bigint,
  'title' : string,
  'link' : string,
  'createdAt' : bigint,
  'enabled' : boolean,
  'summary' : string,
  'imageUrl' : string,
  'category' : string,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'createdAt' : bigint,
  'description' : string,
  'orderType' : string,
  'imageUrl' : [] | [string],
  'customerId' : bigint,
  'providerId' : bigint,
}
export type PlanType = { 'pending' : null } |
  { 'premium' : null } |
  { 'free' : null };
export interface ProviderProfile {
  'userId' : bigint,
  'subscriptionExpiry' : [] | [bigint],
  'subscriptionPlan' : SubscriptionPlan,
  'description' : string,
  'approvalStatus' : ApprovalStatus,
  'subscriptionStatus' : SubscriptionStatus,
  'paymentScreenshotBlobId' : [] | [string],
  'address' : string,
  'serviceRates' : Array<ServiceRate>,
  'upiId' : string,
  'shopName' : string,
  'category' : string,
  'qrCodeBlobId' : [] | [string],
  'planType' : PlanType,
  'photos' : Array<string>,
}
export interface ScrapRate {
  'id' : bigint,
  'ratePerKg' : number,
  'enabled' : boolean,
  'ratePerGram' : number,
  'itemName' : string,
}
export interface ServiceRate {
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export type SubscriptionPlan = { 'twelveMonths' : null } |
  { 'threeMonths' : null } |
  { 'oneMonth' : null };
export interface SubscriptionPricing {
  'threeMonthPrice' : bigint,
  'twelveMonthPrice' : bigint,
  'oneMonthPrice' : bigint,
}
export type SubscriptionStatus = { 'active' : null } |
  { 'expired' : null } |
  { 'pending' : null } |
  { 'rejected' : null };
export interface UdhaarCustomer {
  'id' : string,
  'shopId' : string,
  'name' : string,
  'createdAt' : bigint,
  'address' : string,
  'mobile' : string,
}
export interface UdhaarTransaction {
  'id' : string,
  'status' : string,
  'transactionType' : string,
  'shopId' : string,
  'date' : string,
  'note' : string,
  'createdAt' : bigint,
  'customerId' : string,
  'amount' : number,
}
export interface User {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'role' : UserRole,
  'securityQuestion' : string,
  'securityAnswer' : string,
  'passwordHash' : string,
  'mobile' : MobileNumber,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'userId' : bigint,
  'name' : string,
  'role' : UserRole,
  'mobile' : MobileNumber,
}
export type UserRole = { 'admin' : null } |
  { 'provider' : null } |
  { 'customer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoItem {
  'id' : bigint,
  'title' : string,
  'thumbnailUrl' : string,
  'createdAt' : bigint,
  'platform' : string,
  'enabled' : boolean,
  'category' : string,
  'videoUrl' : string,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addBanner' : ActorMethod<[string, string, string, string, bigint], bigint>,
  'addCategory' : ActorMethod<[string, string, string], bigint>,
  'addCustomCode' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'addJob' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'addNews' : ActorMethod<[string, string, string, string, string], bigint>,
  'addScrapRate' : ActorMethod<[string, number, number], bigint>,
  'addServiceRate' : ActorMethod<[bigint, ServiceRate], undefined>,
  'addShopPhoto' : ActorMethod<[bigint, string], undefined>,
  /**
   * / Add a customer under the calling provider's shop.
   * / shopId is derived from msg.caller — never accepted from the client.
   */
  'addUdhaarCustomer' : ActorMethod<
    [string, string, string],
    { 'ok' : UdhaarCustomer } |
      { 'err' : string }
  >,
  /**
   * / Add a transaction. shopId is derived from caller; customerId must belong to caller.
   */
  'addUdhaarTransaction' : ActorMethod<
    [string, number, string, string, string],
    { 'ok' : UdhaarTransaction } |
      { 'err' : string }
  >,
  'addVideo' : ActorMethod<[string, string, string, string, string], bigint>,
  'approveProvider' : ActorMethod<[bigint, SubscriptionPlan], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'changeAdminPin' : ActorMethod<[string, string], undefined>,
  'deleteBanner' : ActorMethod<[bigint], undefined>,
  'deleteCategory' : ActorMethod<[bigint], boolean>,
  'deleteCustomCode' : ActorMethod<[bigint], boolean>,
  'deleteJob' : ActorMethod<[bigint], boolean>,
  'deleteNews' : ActorMethod<[bigint], boolean>,
  'deleteScrapRate' : ActorMethod<[bigint], boolean>,
  'deleteServiceRate' : ActorMethod<[bigint, string], undefined>,
  /**
   * / Delete a customer and all its transactions. Caller must own the customer.
   */
  'deleteUdhaarCustomer' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Delete a transaction. Caller must own the transaction.
   */
  'deleteUdhaarTransaction' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteVideo' : ActorMethod<[bigint], boolean>,
  'editBanner' : ActorMethod<
    [bigint, string, string, string, string, boolean, bigint],
    undefined
  >,
  'forgotPassword' : ActorMethod<[MobileNumber, string, string], undefined>,
  'getActiveBanners' : ActorMethod<[], Array<Banner>>,
  'getActiveProviders' : ActorMethod<[], Array<ProviderProfile>>,
  'getAdminConfig' : ActorMethod<[], [] | [AdminConfig]>,
  'getAllProviders' : ActorMethod<[], Array<ProviderProfile>>,
  'getAllToggles' : ActorMethod<[], Array<[string, boolean]>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getAppSettings' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getCustomCodes' : ActorMethod<[], Array<CustomCode>>,
  'getCustomerOrders' : ActorMethod<[bigint], Array<Order>>,
  'getJobs' : ActorMethod<[], Array<JobItem>>,
  'getNews' : ActorMethod<[], Array<NewsItem>>,
  'getOrderById' : ActorMethod<[bigint], [] | [Order]>,
  'getOrdersByStatus' : ActorMethod<[bigint, string], Array<Order>>,
  'getProviderOrders' : ActorMethod<[bigint], Array<Order>>,
  'getProviderProfile' : ActorMethod<[bigint], [] | [ProviderProfile]>,
  'getProvidersByCategory' : ActorMethod<[string], Array<ProviderProfile>>,
  'getProvidersPendingApproval' : ActorMethod<[], Array<ProviderProfile>>,
  'getRecentUsers' : ActorMethod<[], Array<User>>,
  'getScrapRates' : ActorMethod<[], Array<ScrapRate>>,
  'getSubscriptionPricing' : ActorMethod<[], [] | [SubscriptionPricing]>,
  /**
   * / Return balance for a customer. Caller must own the customer.
   */
  'getUdhaarBalance' : ActorMethod<
    [string],
    { 'ok' : number } |
      { 'err' : string }
  >,
  /**
   * / Return only customers belonging to the calling provider.
   * / shopId is derived from msg.caller — no user-supplied filter accepted.
   */
  'getUdhaarCustomers' : ActorMethod<[], Array<UdhaarCustomer>>,
  /**
   * / Return transactions for a customer. Caller must own the customer.
   */
  'getUdhaarTransactions' : ActorMethod<
    [string],
    { 'ok' : Array<UdhaarTransaction> } |
      { 'err' : string }
  >,
  'getUserById' : ActorMethod<[bigint], [] | [User]>,
  'getUserByMobile' : ActorMethod<[MobileNumber], [] | [User]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsersByRole' : ActorMethod<[UserRole], Array<User>>,
  'getVideos' : ActorMethod<[], Array<VideoItem>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'login' : ActorMethod<[MobileNumber, string], User>,
  /**
   * / Mark a transaction as paid. Caller must own the transaction.
   */
  'markUdhaarTransactionPaid' : ActorMethod<
    [string],
    { 'ok' : UdhaarTransaction } |
      { 'err' : string }
  >,
  'placeOrder' : ActorMethod<
    [bigint, string, string, string, [] | [string]],
    bigint
  >,
  'registerUser' : ActorMethod<
    [string, MobileNumber, string, UserRole, string, string],
    undefined
  >,
  'rejectProvider' : ActorMethod<[bigint], undefined>,
  'removeShopPhoto' : ActorMethod<[bigint, string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUsers' : ActorMethod<[string], Array<User>>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setPlanType' : ActorMethod<[bigint, PlanType], undefined>,
  'updateAdminConfig' : ActorMethod<[AdminConfig], undefined>,
  'updateAppSettings' : ActorMethod<[string], undefined>,
  'updateCategory' : ActorMethod<
    [bigint, string, string, string, boolean],
    boolean
  >,
  'updateCustomCode' : ActorMethod<
    [bigint, string, string, string, string, string, boolean],
    boolean
  >,
  'updateJob' : ActorMethod<
    [bigint, string, string, string, string, string, string, boolean],
    boolean
  >,
  'updateNews' : ActorMethod<
    [bigint, string, string, string, string, string, boolean],
    boolean
  >,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
  'updateProviderProfile' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  /**
   * / Extended updateProviderProfile to include upiId and qrCodeBlobId
   */
  'updateProviderProfileFull' : ActorMethod<
    [bigint, string, string, string, string, string, [] | [string]],
    undefined
  >,
  'updateScrapRate' : ActorMethod<
    [bigint, string, number, number, boolean],
    boolean
  >,
  'updateSubscriptionPricing' : ActorMethod<[SubscriptionPricing], undefined>,
  'updateToggle' : ActorMethod<[string, boolean], undefined>,
  /**
   * / Update a customer. Caller must own the customer (shopId check).
   */
  'updateUdhaarCustomer' : ActorMethod<
    [string, string, string, string],
    { 'ok' : UdhaarCustomer } |
      { 'err' : string }
  >,
  /**
   * / Update a transaction. Caller must own the transaction (shopId check).
   */
  'updateUdhaarTransaction' : ActorMethod<
    [string, number, string, string, string],
    { 'ok' : UdhaarTransaction } |
      { 'err' : string }
  >,
  'updateVideo' : ActorMethod<
    [bigint, string, string, string, string, string, boolean],
    boolean
  >,
  'uploadPaymentScreenshot' : ActorMethod<[bigint, string], undefined>,
  'verifyAdminPin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];