/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminConfig {
  'email' : string,
  'adminName' : string,
  'upiId' : string,
  'mobile' : MobileNumber,
  'qrCodeBlobId' : ExternalBlob,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Banner {
  'id' : bigint,
  'title' : string,
  'active' : boolean,
  'linkUrl' : string,
  'displayOrder' : bigint,
  'imageUrl' : string,
  'subtitle' : string,
}
export type ExternalBlob = Uint8Array;
export type MobileNumber = string;
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'createdAt' : bigint,
  'description' : string,
  'orderType' : string,
  'imageUrl' : [] | [string],
  'customerId' : bigint,
  'providerId' : bigint,
}
export type PlanType = { 'pending' : null } |
  { 'premium' : null } |
  { 'free' : null };
export interface ProviderProfile {
  'userId' : bigint,
  'subscriptionExpiry' : [] | [bigint],
  'subscriptionPlan' : SubscriptionPlan,
  'description' : string,
  'approvalStatus' : ApprovalStatus,
  'subscriptionStatus' : SubscriptionStatus,
  'paymentScreenshotBlobId' : [] | [string],
  'address' : string,
  'serviceRates' : Array<ServiceRate>,
  'upiId' : string,
  'shopName' : string,
  'category' : string,
  'qrCodeBlobId' : [] | [string],
  'planType' : PlanType,
  'photos' : Array<string>,
}
export interface ServiceRate {
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export type SubscriptionPlan = { 'twelveMonths' : null } |
  { 'threeMonths' : null } |
  { 'oneMonth' : null };
export interface SubscriptionPricing {
  'threeMonthPrice' : bigint,
  'twelveMonthPrice' : bigint,
  'oneMonthPrice' : bigint,
}
export type SubscriptionStatus = { 'active' : null } |
  { 'expired' : null } |
  { 'pending' : null } |
  { 'rejected' : null };
export interface User {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'role' : UserRole,
  'securityQuestion' : string,
  'securityAnswer' : string,
  'passwordHash' : string,
  'mobile' : MobileNumber,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'userId' : bigint,
  'name' : string,
  'role' : UserRole,
  'mobile' : MobileNumber,
}
export type UserRole = { 'admin' : null } |
  { 'provider' : null } |
  { 'customer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addBanner' : ActorMethod<[string, string, string, string, bigint], bigint>,
  'addServiceRate' : ActorMethod<[bigint, ServiceRate], undefined>,
  'addShopPhoto' : ActorMethod<[bigint, string], undefined>,
  'approveProvider' : ActorMethod<[bigint, SubscriptionPlan], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'changeAdminPin' : ActorMethod<[string, string], undefined>,
  'deleteBanner' : ActorMethod<[bigint], undefined>,
  'deleteServiceRate' : ActorMethod<[bigint, string], undefined>,
  'editBanner' : ActorMethod<
    [bigint, string, string, string, string, boolean, bigint],
    undefined
  >,
  'forgotPassword' : ActorMethod<[MobileNumber, string, string], undefined>,
  'getActiveBanners' : ActorMethod<[], Array<Banner>>,
  'getActiveProviders' : ActorMethod<[], Array<ProviderProfile>>,
  'getAdminConfig' : ActorMethod<[], [] | [AdminConfig]>,
  'getAllProviders' : ActorMethod<[], Array<ProviderProfile>>,
  'getAllToggles' : ActorMethod<[], Array<[string, boolean]>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCustomerOrders' : ActorMethod<[bigint], Array<Order>>,
  'getOrderById' : ActorMethod<[bigint], [] | [Order]>,
  'getOrdersByStatus' : ActorMethod<[bigint, string], Array<Order>>,
  'getProviderOrders' : ActorMethod<[bigint], Array<Order>>,
  'getProviderProfile' : ActorMethod<[bigint], [] | [ProviderProfile]>,
  'getProvidersByCategory' : ActorMethod<[string], Array<ProviderProfile>>,
  'getProvidersPendingApproval' : ActorMethod<[], Array<ProviderProfile>>,
  'getRecentUsers' : ActorMethod<[], Array<User>>,
  'getSubscriptionPricing' : ActorMethod<[], [] | [SubscriptionPricing]>,
  'getUserById' : ActorMethod<[bigint], [] | [User]>,
  'getUserByMobile' : ActorMethod<[MobileNumber], [] | [User]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsersByRole' : ActorMethod<[UserRole], Array<User>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'login' : ActorMethod<[MobileNumber, string], User>,
  'placeOrder' : ActorMethod<
    [bigint, string, string, string, [] | [string]],
    bigint
  >,
  'registerUser' : ActorMethod<
    [string, MobileNumber, string, UserRole, string, string],
    undefined
  >,
  'rejectProvider' : ActorMethod<[bigint], undefined>,
  'removeShopPhoto' : ActorMethod<[bigint, string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUsers' : ActorMethod<[string], Array<User>>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setPlanType' : ActorMethod<[bigint, PlanType], undefined>,
  'updateAdminConfig' : ActorMethod<[AdminConfig], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
  'updateProviderProfile' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  /**
   * / Extended updateProviderProfile to include upiId and qrCodeBlobId
   */
  'updateProviderProfileFull' : ActorMethod<
    [bigint, string, string, string, string, string, [] | [string]],
    undefined
  >,
  'updateSubscriptionPricing' : ActorMethod<[SubscriptionPricing], undefined>,
  'updateToggle' : ActorMethod<[string, boolean], undefined>,
  'uploadPaymentScreenshot' : ActorMethod<[bigint, string], undefined>,
  'verifyAdminPin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];